### ISSUE TITLE
Fit fishery/survey model with 2023 data

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [AndreaNOdell/hake_growth#11]
@AndreaNOdell is there any way you can either point me to the correct files to run or perhaps run a non-spatial model with the 2023 survey and fishery data included?

**Comment by AndreaNOdell** [comment]
Hi Kelli! I have not ran a model with the recent data, but can do that now. I had a look at the [Hake Assessment github folder](https://github.com/pacific-hake/hake-assessment/tree/master/data-tables/length-weight-age) where I got the fishery weight data and there doesn't seem to be info for 2023. However, I looked around and found 2023 data for the [CAN fishery (can-weight-at-age.csv)](https://github.com/pacific-hake/hake-assessment/blob/master/data-tables/can-weight-at-age.csv), [US Fishery (us-weight-at-age.csv)](https://github.com/pacific-hake/hake-assessment/blob/master/data-tables/us-weight-at-age.csv), and the [survey (survey-weight-at-age)](https://github.com/pacific-hake/hake-assessment/blob/master/data-tables/survey-weight-at-age.csv), but wanted to check with you if that is correct before I start. Thank you!

**Comment by kellijohnson-NOAA** [comment]
Yes those are the correct files. We are trying to clean up our repository, hence the new file structure of everything being in data-tables. Let me know if you need any help. Also, these three files contain all of the data currently being used so you will not have to bring in any other files.

**Comment by AndreaNOdell** [comment]
Great - I like the simplicity of these data files! I'll let you know when the model is complete.

**Comment by AndreaNOdell** [comment]
The [EWAA](https://github.com/AndreaNOdell/hake_growth/blob/master/outputs/EWAA_fishery_survey_nospatial_1975-2023_wide.csv) is up and ready to use (find it in outputs/EWAA_fishery_survey_nospatial_1975-2023_wide.csv). 

I fit a non-spatial model to the 1975-2023 fishery and survey data with age, cohort, year, and sex effects.

**Comment by kellijohnson-NOAA** [comment]
Thank you so much 🥳!
