### ISSUE TITLE
Multiple columns with date information - which to use?

### ISSUE THREAD

**Issue by AndreaNOdell** [AndreaNOdell/hake_growth#2]
In the raw dataset, there are a number of columns that seem to include information on dates relevant to the fish individual collected. Column names include "catch_modified_date", "eq_date", "hb_date", and "specimen_modified_date". I am currently using "eq_date" as that seemed to have the most complete information. Similarly, there is "eq_long", "eq_lat", and "hb_long", "hb_lat". What does eq and hb stand for?

**Comment by AndreaNOdell** [comment]
I found the metadata information!

**Comment by kristinmarshall-NOAA** [comment]
Great!  Did the metadata solve the date question, or do we still need help from the acoustics team to decipher?

**Comment by AndreaNOdell** [comment]
I do believe so! I know what each date means now (eq_date = date when target depth was called; hb_date = date when haul back was called). Not 100% sure what haul back is, but the dates seem to be the same between the two. There are slight differences in the lat/long coordinates though (perhaps negligible?).

**Comment by kristinmarshall-NOAA** [comment]
I believe haul back is when they pull the net back in, so that might be the most accurate.  It doesn't seem to matter for the date, like you say, but may have small differences for the coordinates.
