### ISSUE TITLE
weights or lengths?

### ISSUE THREAD

**Issue by kristinmarshall-NOAA** [AndreaNOdell/hake_growth#3]
This is just a thought I had I wanted to capture, and get your thoughts on too.

After reading the Correa et al. paper and thinking about Maia's sablefish growth work, I began to wonder if we should be looking at the lengths in addition to, or instead of the weights? And/or thinking about modeling weight at age rather than the weight at length anomalies.

I think looking at weight deviations from the weight at length curve makes sense, and the data exploration you've done so far has shown some interesting patterns in weight anomalies - e.g. year variation seems larger than spatial variation.  Essentially, those data can answer the question, are fish fatter or skinner for a given length?  It might be interesting if the length data showed similar or different patterns - are fish longer or shorter for a given age?  Or, similarly I guess we could use the weight data to ask, are fish bigger or smaller for a given age (not length).  I would think that the weight anomalies might be more indicative of conditions during a year, or year before, and be more responsive to environmental conditions, and potentially less integrative over the life of a fish - that's a hypothesis.  

From the perspective of the stock assessment - variability in weight at age is the key quantity of interest. But, that wasn't always the case.  In the [2006-2010 assessments](https://www.pcouncil.org/stock-assessments-star-reports-stat-reports-rebuilding-analyses-terms-of-reference/groundfish-stock-assessment-documents/) they modeled growth and length variability.  It might be useful for one of us to take a look at those.  Also, there is [a simulation study by Peter Kuriyama from 2016](https://www.sciencedirect.com/science/article/pii/S0165783615300837?casa_token=3UZyvmJTzOsAAAAA:IqQmSNA36wSX7dYApyhfsHvYX7XohK5r4akOZNRw37t-tr9a8SEuC4dLLYppj8DCFF1P3INWAg) that might help us think about this as well. 

We can talk more about this tomorrow, or after that.

**Comment by AndreaNOdell** [comment]
After doing some reading, it seems like a weight-length relationship is a good indicator of "body condition"  which  is often tied to fitness, reproduction, and physiological health, while weight-at-age has a temporal component, so perhaps a better indicator for growth rate. Might be worth continuing to look at both, but definitely need to think more about how they may relate to each other (or not).

**Comment by kristinmarshall-NOAA** [comment]
Closing this.  Moved forward with weight at age, could further explore condition (weight/length) down the road.
